export const ARTICLES_RECEIVED = 'ARTICLES_RECEIVED';
export const ARTICLES_NOT_RECEIVED = 'ARTICLES_NOT_RECEIVED';
export const RESET = 'RESET';
export const AUTH_COMPLETED = 'AUTH_COMPLETED';
export const LOG_OUT = 'LOG_OUT';
export const SERVER_VALIDATIONS_RECEIVED = 'SERVER_VALIDATIONS_RECEIVED';
export const AUTH_NOT_COMPLETED = 'AUTH_NOT_COMPLETED';