export const GET_ARTICLES_$_LOADING = 'GET_ARTICLES_$_LOADING';
export const GET_ARTICLES_$_RECEIVED = 'GET_ARTICLES_$_RECEIVED';
export const GET_ARTICLES_$_NOT_RECEIVED = 'GET_ARTICLES_$_NOT_RECEIVED';

export const GET_ARTICLE_$_LOADING = 'GET_ARTICLE_$_LOADING';
export const GET_ARTICLE_$_RECEIVED = 'GET_ARTICLE_$_RECEIVED';
export const GET_ARTICLE_$_NOT_RECEIVED = 'GET_ARTICLE_$_NOT_RECEIVED';

export const AUTH_$_LOADING = 'AUTH_$_LOADING';
export const AUTH_$_COMPLETED = 'AUTH_$_COMPLETED';
export const AUTH_$_NOT_COMPLETED = 'AUTH_$_NOT_COMPLETED';
export const AUTH_$_SERVER_VALIDATION = 'AUTH_$_SERVER_VALIDATION';
export const AUTH_$_RESET = 'AUTH_$_RESET';

export const REGISTRATION_$_COMPLETED = 'REGISTRATION_$_COMPLETED';
export const REGISTRATION_$_LOADING = 'REGISTRATION_$_LOADING';
export const REGISTRATION_$_NOT_COMPLETED = 'REGISTRATION_$_NOT_COMPLETED';
export const REGISTRATION_$_SERVER_VALIDATION = 'REGISTRATION_$_SERVER_VALIDATION';
export const REGISTRATION_$_RESET = 'REGISTRATION_$_RESET';

export const LOG_OUT = 'LOG_OUT';

export const EDIT_PROFILE_$_LOADING = 'EDIT_PROFILE_$_LOADING';
export const EDIT_PROFILE_$_EDITED = 'EDIT_PROFILE_$_EDITED';
export const EDIT_PROFILE_$_NOT_EDITED = 'EDIT_PROFILE_$_NOT_EDITED';
export const EDIT_PROFILE_$_SERVER_VALIDATION = 'EDIT_PROFILE_$_SERVER_VALIDATION';
export const EDIT_PROFILE_$_RESET = 'EDIT_PROFILE_$_RESET';

export const CREATE_ARTICLE_$_LOADING = 'CREATE_ARTICLE_$_LOADING';
export const CREATE_ARTICLE_$_CREATED = 'CREATE_ARTICLE_$_CREATED';
export const CREATE_ARTICLE_$_NOT_CREATED = 'CREATE_ARTICLE_$_NOT_CREATED';
export const CREATE_ARTICLE_$_RESET = 'CREATE_ARTICLE_$_RESET';

export const EDIT_ARTICLE_$_LOADING = 'EDIT_ARTICLE_$_LOADING';
export const EDIT_ARTICLE_$_EDITED = 'EDIT_ARTICLE_$_EDITED';
export const EDIT_ARTICLE_$_NOT_EDITED = 'EDIT_ARTICLE_$_NOT_EDITED';
export const EDIT_ARTICLE_$_RESET = 'EDIT_ARTICLE_$_RESET';

export const DELETE_ARTICLE_$_LOADING = 'DELETE_ARTICLE_$_LOADING';
export const DELETE_ARTICLE_$_DELETED = 'DELETE_ARTICLE_$_DELETED';
export const DELETE_ARTICLE_$_NOT_DELETED = 'DELETE_ARTICLE_$_NOT_DELETED';
export const DELETE_ARTICLE_$_RESET = 'DELETE_ARTICLE_$_RESET';

export const FAVORITE_ARTICLE_$_LOADING = 'FAVORITE_ARTICLE_$_LOADING';
export const FAVORITE_ARTICLE_$_ADDED = 'FAVORITE_ARTICLE_$_ADDED';
export const FAVORITE_ARTICLE_$_NOT_ADDED = 'FAVORITE_ARTICLE_$_NOT_ADDED';
export const FAVORITE_ARTICLE_$_RESET = 'FAVORITE_ARTICLE_$_RESET';