export const ARTICLES_RECEIVED = 'ARTICLES_RECEIVED';
export const ARTICLES_NOT_RECEIVED = 'ARTICLES_NOT_RECEIVED';
export const BEGINNING = 'BEGINNING';
export const AUTH_COMPLETED = 'AUTH_COMPLETED';
export const LOG_OUT = 'LOG_OUT';
export const SERVER_VALIDATIONS_RECEIVED = 'SERVER_VALIDATIONS_RECEIVED';